server:
  port: ${SERVER_PORT:8087}

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:rental_user}
    password: ${MYSQL_PASSWORD:rental_secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:rental_rabbit}
    password: ${RABBITMQ_DEFAULT_PASS:rental_rabbit_secret}

rental:
  rabbitmq:
    exchange: rental.topic.exchange
    routing-key:
      payment-completed: payment.completed
  vnpay:
    tmn-code: ${VNPAY_TMN_CODE:JDWJCCLC}
    hash-secret: ${VNPAY_HASH_SECRET:RFQIDMWHCGBYGTCJPIGLEVGQGNQKAJGM}
    pay-url: ${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    return-url: ${VNPAY_RETURN_URL:http://localhost:5173/payment/vnpay-return}
  momo:
    partner-code: ${MOMO_PARTNER_CODE:MOMO}
    access-key: ${MOMO_ACCESS_KEY:F8BBA842ECF85}
    secret-key: ${MOMO_SECRET_KEY:K951B6PE1waDMi640xX08PD3vg6EkVlz}
    endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
    redirect-url: ${MOMO_REDIRECT_URL:http://localhost:5173/payment/momo-return}
    ipn-url: ${MOMO_IPN_URL:http://localhost:8087/api/payments/momo/ipn}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,actuator
  endpoint:
    health:
      show-details: always
